import { Button } from "../button.slint";

export component SSHUsbNet inherits Rectangle {
    in property <length> root-height;

    callback toggle-ota();

    VerticalLayout {
        height: root-height * 0.27;
        y: root-height * 0.07;
        alignment: center;
        spacing: root-height * 0.02;

        Text {
            color: black;
            wrap: word-wrap;
            width: 100%;
            font-size: root-height * 0.027;
            font-family: "Inter";
            horizontal-alignment: center;
            vertical-alignment: center;
            text: "SSH networking is currently disabled.";
        }

        HorizontalLayout {
            alignment: center;

            VerticalLayout {
                spacing: root-height * 0.02;

                Button {
                    root-height: root-height;
                    text: "Enable USB SSH";
                    width: root-height * 0.5;
                }

                Button {
                    root-height: root-height;
                    text: "Enable Wi-Fi SSH";
                    width: root-height * 0.5;
                }
            }
        }

        Text {
            text: "IP: 192.168.1.1\nMode: N/A (please select)\nConfig is mandated in ~/jobman/ssh.properties";
            color: #4b5563;
            wrap: word-wrap;
            width: 100%;
            font-size: root.width * 0.03;
            font-family: "Inter";
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }
}
