import { Button } from "../button.slint";

export component SSHUsbNet inherits Rectangle {
    in property <length> root-height;
    in property <string> usb-ssh-ip: "N/A";
    in property <string> wifi-ssh-ip: "N/A";
    private property <string> connection-mode: root.usb-ssh-status ? "USB" : (root.wifi-ssh-status ? "Wi-Fi" : "N/A (select mode)");
    in-out property <bool> usb-ssh-status: false;
    in property <bool> wifi-ssh-status: false;

    callback usb-ssh-toggle();
    callback wifi-ssh-toggle();

    VerticalLayout {
        height: root-height * 0.27;
        y: root.usb-ssh-status || root.wifi-ssh-status ? root-height * 0.12 : root-height * 0.07;
        alignment: center;
        spacing: root-height * 0.02;

        Text {
            color: black;
            wrap: word-wrap;
            width: 100%;
            font-size: root-height * 0.027;
            font-family: "Inter";
            horizontal-alignment: center;
            vertical-alignment: center;
            text: root.usb-ssh-status || root.wifi-ssh-status ? "SSH networking is currently enabled!" : "SSH networking is currently disabled.";
        }

        HorizontalLayout {
            alignment: center;

            VerticalLayout {
                spacing: root-height * 0.02;

                if root.wifi-ssh-status == false: Button {
                    root-height: root-height;
                    text: root.usb-ssh-status ? "Disable USB SSH" : "Enable USB SSH";
                    width: root-height * 0.5;
                    clicked => { 
                        usb-ssh-toggle();
                    }
                }

                if root.usb-ssh-status == false: Button {
                    root-height: root-height;
                    text: root.wifi-ssh-status ? "Disable Wi-Fi SSH" : "Enable Wi-Fi SSH";
                    width: root-height * 0.5;
                    clicked => {
                        wifi-ssh-toggle();
                    }
                }
            }
        }

        Text {
            text: "IP: " + (!root.usb-ssh-status && !root.wifi-ssh-status ? "N/A (select mode)" : (root.usb-ssh-status ? root.usb-ssh-ip : root.wifi-ssh-ip))  + "\nMode: " + root.connection-mode + "\nConfig is mandated in ~/jobman/ssh/etc/config.toml";
            color: #4b5563;
            wrap: word-wrap;
            width: 100%;
            font-size: root.width * 0.03;
            font-family: "Inter";
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }
}
