import { Button } from "../button.slint";

export component SSHUsbNet inherits Rectangle {
    in property <length> root-height;
    in property <string> kindle-ssh-ip: "N/A";
    private property <string> mode: "N/A (please select)";
    in property <bool> usb-ssh-status: false;

    callback usb-ssh-toggle();

    VerticalLayout {
        height: root-height * 0.27;
        y: root-height * 0.07;
        alignment: center;
        spacing: root-height * 0.02;

        Text {
            color: black;
            wrap: word-wrap;
            width: 100%;
            font-size: root-height * 0.027;
            font-family: "Inter";
            horizontal-alignment: center;
            vertical-alignment: center;
            text: root.usb-ssh-status ? "SSH networking is currently enabled!" : "SSH networking is currently disabled.";
        }

        HorizontalLayout {
            alignment: center;

            VerticalLayout {
                spacing: root-height * 0.02;

                Button {
                    root-height: root-height;
                    text: root.usb-ssh-status ? "Disable USB SSH" : "Enable USB SSH";
                    width: root-height * 0.5;
                    clicked => { 
                        usb-ssh-toggle();
                        root.mode = root.usb-ssh-status ? "USB" : "N/A (please select)";
                    }
                }

                if root.usb-ssh-status == false: Button {
                    root-height: root-height;
                    text: "Enable Wi-Fi SSH";
                    width: root-height * 0.5;
                }
            }
        }

        Text {
            text: "IP: " + root.kindle-ssh-ip + "\nMode: " + root.mode + "\nConfig is mandated in ~/jobman/ssh/etc/config";
            color: #4b5563;
            wrap: word-wrap;
            width: 100%;
            font-size: root.width * 0.03;
            font-family: "Inter";
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }
}
