import { Card } from "card.slint";
import { Button } from "button.slint";
import { UpdateBlocking } from "pages/update-blocking.slint";
import { BatteryHealth } from "pages/battery-health.slint";
import { EnvironmentUpdate } from "pages/environment-update.slint";
import { Background } from "background.slint";
import { SSHUsbNet } from "pages/ssh-usb-net.slint";

/*
    This project scales relative to root.height, 
    so long as all proportions remain sensible in a portrait position as well as as a square one (Oasis).
*/

export component AppWindow inherits Window {
    background: white;

    in property <bool> boot-mode: false;
    in property <string> usb-ssh-ip: "N/A";
    in property <string> wifi-ssh-ip: "N/A";
    in property <string> boot-reason: "N/A";
    in property <string> jobman-version: "1.0.0";
    in property <bool> ota-status: false;
    in property <bool> wifi-status: false;
    in property <bool> usb-ssh-status: false;
    in property <bool> wifi-ssh-status: false;
    in property <int> battery-health: 100;
    private property <bool> updating-env: false;
    private property <bool> ota-renaming: false;
    private property <string> view: "home";
    in-out property <bool> show-error: false;
    in-out property <string> error: "An unknown error occurred. Please retry at another time.";

    callback quit();
    callback toggle_ota();
    callback update_environment();
    callback usb_ssh_toggle();
    callback wifi_ssh_toggle();

    Background {}

    //Header content
    Rectangle {
        x: root.width - self.width - root.width * 0.03;
        y: root.height * 0.02;
        width: root.width * 0.1;
        height: root.width * 0.1;
        border-width: root.width * 0.005;
        border-color: black;
        border-radius: root.width * 0.015;
        background: quit-touch.pressed ? #cccccc : white;

        quit-touch := TouchArea {
            clicked => { 
                if view == "home" { root.quit(); }
                if view != "home" { root.view = "home" } 
            }
        }

        VerticalLayout {
            alignment: center;

            HorizontalLayout {
                alignment: center;
                if view == "home": Text {
                    text: "×";
                    font-size: root.width * 0.07;
                    font-family: "Libre Baskerville"; //Inter ruins centering.
                    color: black;
                    font-weight: 800; 
                }

                if view != "home": Text {
                    text: "←";
                    font-family: "Libre Baskerville";
                    font-size: root.width * 0.06;
                    color: black;
                }
            }
        }
    }

    VerticalLayout {
        height: root.height * 0.05;
        y: root.height * 0.12;
        alignment: center;
        spacing: root.height * 0.015; 

        Text {
            x: 0;
            width: parent.width;
            text: "Jobman";
            font-size: root.width * 0.15;
            font-family: "Libre Baskerville";
            color: black;
            horizontal-alignment: center;
        }

        Text {
            x: 0;
            width: parent.width;
            text: root.boot-mode ? "Your Friendly Recovery Menu" : "Your Friendly Jailbreaking Manager";
            font-family: "Inter";
            font-size: root.width * 0.04;
            color: black;
            horizontal-alignment: center;
        }
    }

    //Main content
    Rectangle {
        x: root.width * 0.05; //Left margin 
        width: root.width * 0.9; //100% - 5% ^ - 5%.
        y: root.height * 0.37;

        if view == "home": VerticalLayout {
            spacing: root.height * 0.01; 

            if !root.boot-mode: Card {
               root-height: root.height;
               title: "Update Blocking";
               description: "Manage the enabling & disabling of OTA binaries";
               clicked => { root.view = "update-blocking" }
            }

            Card {
                root-height: root.height;
                title: "SSH & USB Networking";
                description: root.boot-mode ? "Start an emergency SSH over USB server" : "Start an SSH server over USB or Wi-Fi";
                clicked => { root.view = "ssh-usb-net" }
            }

            if root.boot-mode: Card {
                root-height: root.height;
                title: "Mount Userstore";
                description: "Mount the Kindle over USB";
            }

            if root.boot-mode: Card {
                root-height: root.height;
                title: "Wipe Userstore";
                description: "Recreate the userstore (/mnt/us)";
            }

            if root.boot-mode: Card {
                root-height: root.height;
                title: "Reboot to Jobman";
                description: "Exit & reboot back to Jobman recovery";
            }

            if !root.boot-mode: Card {
               root-height: root.height;
               title: "Environment Update";
               description: "Update the jailbreaking environment";
               clicked => { root.view = "environment-update" }
            }

            if !root.boot-mode: Card {
               root-height: root.height;
               title: "Battery Health";
               description: "Automatic battery checking utility";
               clicked => { root.view = "battery-health" }
            }

            if !root.boot-mode: Card {
               root-height: root.height;
               title: "Update Jobman";
               description: "Check for jailbreak manager updates";
            }
        }

        if view == "update-blocking": UpdateBlocking {
            root-height: root.height;
            ota-status: root.ota-status;
            ota-renaming <=> root.ota-renaming;
            toggle-ota => {
                root.toggle_ota();
            }
        }

        if view == "ssh-usb-net": SSHUsbNet {
            root-height: root.height;
            usb-ssh-ip: root.usb-ssh-ip;
            wifi-ssh-ip: root.wifi-ssh-ip;
            usb-ssh-status: root.usb-ssh-status;
            wifi-ssh-status: root.wifi-ssh-status;
            usb-ssh-toggle => {
                root.usb_ssh_toggle();
            }
            wifi-ssh-toggle => {
                root.wifi_ssh_toggle();
            }
        }

        if view == "environment-update": EnvironmentUpdate {
            root-height: root.height;
            wifi-status: root.wifi-status;
            updating-env <=> root.updating-env;
            update-environment => {
                root.update_environment();
            }
        }

        if view == "battery-health": BatteryHealth {
            root-height: root.height;
            battery-health: root.battery-health;
        }
    }

    Text {
        x: 0;
        y: root.boot-mode ? root.height * 0.87 : root.height * 0.95;
        width: parent.width;
        text: root.boot-mode ? "Reason: " + root.boot-reason + "\nhttps://kindlemodding.org/recovery\nMade by KindleTweaks | v" + root.jobman-version : "Made by KindleTweaks | v" + root.jobman-version;
        font-size: root.width * 0.03;
        color: #4b5563;
        horizontal-alignment: center;
    }
    
    //Error Dialog
    if root.show-error: TouchArea {
        clicked => {}

        Rectangle {
            background: #000000aa; 
        }

        VerticalLayout {
            alignment: center;
            HorizontalLayout {
                alignment: center;
                Rectangle {
                    background: white;
                    border-radius: root.width * 0.05;
                    width: root.width * 0.8;
                    border-width: root.width * 0.005;
                    border-color: black;

                    VerticalLayout {
                        padding: root.width * 0.08;
                        spacing: root.height * 0.05;

                        Text {
                            text: "Error Occurred";
                            font-family: "Libre Baskerville";
                            font-size: root.width * 0.07;
                            color: black;
                        }

                        Text {
                            text: root.error;
                            font-family: "Inter";
                            color: black;
                            font-size: root.width * 0.03;
                            wrap: word-wrap;
                            vertical-alignment: center;
                        }

                        Button {
                            root-height: root.height;
                            text: "Dismiss";
                            clicked => {
                                root.show-error = false;
                                root.ota-renaming = false; 
                                root.updating-env = false;
                            }
                        }
                    }
                }
            }   
        }
    }
}